#!/bin/sh

# This script was generated by Nix.
# To make changes edit nix configuration.

echo "->> Running 'build'"
# Dependencies for build

# Run build task
cargo build --release --manifest-path "`git rev-parse --show-toplevel`/././Cargo.toml"

