#!/bin/sh

# This script was generated by Nix.
# To make changes edit nix configuration.

echo "->> Running 'demo-package'"
# Dependencies for demo-package
echo "--->> Running 'document'"
# Dependencies for document

# Run document task
rm -rf target/doc
cargo doc --no-deps


echo "--->> Running 'demo-build'"
# Dependencies for demo-build

# Run demo-build task
wasm-pack build --target web "`git rev-parse --show-toplevel`/demo"


# Run demo-package task
root="`git rev-parse --show-toplevel`"
output="$root/public"
mkdir -p "$output"
echo "Copying demo files to $output"
cp -r "$root/demo/pkg" "$output"
cp "$root/demo/favicon.ico" "$output"
cp "$root/demo/index.html" "$output"
cp "$root/demo/styles.css" "$output"
cp "$root/demo/index.js" "$output"
echo "Copying documentation to $output/doc"
cp -r "$root/target/doc" "$output/doc"

