#!/bin/sh

# This script was generated by Nix.
# To make changes edit nix configuration.

echo "->> Running 'demo-package'"
# Dependencies for demo-package
echo "--->> Running 'demo-build'"
# Dependencies for demo-build

# Run demo-build task
wasm-pack build --target web "`git rev-parse --show-toplevel`/demo"


echo "--->> Running 'demo-generate-favicon'"
# Dependencies for demo-generate-favicon

# Run demo-generate-favicon task
root="`git rev-parse --show-toplevel`"
echo "Stupid Shader Language" | cargo run -- /dev/stdin -W 100 -H 100 -o $root/demo/favicon.png
mv -v $root/demo/favicon.png $root/demo/favicon.ico


# Run demo-package task
root="`git rev-parse --show-toplevel`"
mkdir -p "$root/demo/public"
cp -rv "$root/demo/pkg" "$root/demo/public"
cp -v "$root/demo/favicon.ico" "$root/demo/public"
cp -v "$root/demo/index.html" "$root/demo/public"
cp -v "$root/demo/index.css" "$root/demo/public"
cp -v "$root/demo/index.js" "$root/demo/public"

